// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"simple_bank/db/models"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (models.Account, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (models.Account, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]models.Account, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (models.Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (models.Entry, error)
	DeleteEntry(ctx context.Context, id int64) error
	GetEntry(ctx context.Context, id int64) (models.Entry, error)
	ListEntry(ctx context.Context, arg ListEntryParams) ([]models.Entry, error)
	UpdateEntry(ctx context.Context, arg UpdateEntryParams) (models.Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (models.Transfer, error)
	DeleteTransfer(ctx context.Context, id int64) error
	GetTransfer(ctx context.Context, id int64) (models.Transfer, error)
	ListTransfer(ctx context.Context, arg ListTransferParams) ([]models.Transfer, error)
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) (models.Transfer, error)
}

var _ Querier = (*Queries)(nil)
